import { Geist, Geist_Mono } from "next/font/google";
import NextAuthProvider from "@/providers/nextauth-provider";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Canvas",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthProvider>
          <Suspense>
            {children}
          </Suspense>
        </NextAuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
